@baseUrl = http://localhost:3001
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NzI5MzJmZjExZjI1YTc1YTg4YjIwMSIsImlhdCI6MTc1MjM4ODg5OSwiZXhwIjoxNzUyNDc1Mjk5fQ.dWW1TeIUMJK-Kw_Ok_KzDsOox1jiG0_mwlro9dBkPB4
##-------------------------------------------- USER -------------------------------------------------------------
### add user
POST {{baseUrl}}/api/user
Content-Type: application/json

{
  "name": "moon",
  "email": "moon@gmail.com",
  "password": "moon"
}

### get all users 
GET {{baseUrl}}/api/user/all
Authorization: {{authToken}}

### get logged in user details 
GET {{baseUrl}}/api/user
Authorization: {{authToken}}


##------------------------------------------- AUTH --------------------------------------------------------------
###login user 
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "moon@gmail.com",
  "password": "moon"
}

## ------------------------------------------ MOVIES -------------------------------------------------------------

### get all movies
GET {{baseUrl}}/api/movies
