@baseUrl = http://localhost:3001

##-------------------------------------------- USER -------------------------------------------------------------
### add user
POST {{baseUrl}}/api/user
Content-Type: application/json

## ------------------------------------------ movies -------------------------------------------------------------

### get all movies
GET {{baseUrl}}/api/movies
