@baseUrl = http://localhost:3001
@authToken = Bearer <auth token>
##-------------------------------------------- USER -------------------------------------------------------------
### add user
POST {{baseUrl}}/api/user
Content-Type: application/json

{
  "name": "moon",
  "email": "moon@gmail.com",
  "password": "moon"
}

### get all users 
GET {{baseUrl}}/api/user/all
Authorization: {{authToken}}


##------------------------------------------- AUTH --------------------------------------------------------------
###login user 
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "moon@gmail.com",
  "password": "moon"
}

## ------------------------------------------ MOVIES -------------------------------------------------------------

### get all movies
GET {{baseUrl}}/api/movies
