/**
 * this contains all the constants used in models
 */

export const USER_ROLES = ['user', 'admin'];

export const MEDIA_STATUS = ['released', 'upcoming'];

//@TODO move this db later
export const GENRE_MOVIE_TV = [
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Documentary',
  'Drama',
  'Fantasy',
  'Historical',
  'Horror',
  'Mystery',
  'Romance',
  'Sci-Fi',
  'Thriller',
  'War',
  'Western',
  'Superhero',
  'Family',
  'Musical',
  'Biography',
  'Sport',
  'Noir',
  'Reality',
  'Talk Show',
  'Game Show',
  'News',
  'Cooking',
  'Kids',
  'Indie',
  'RPG',
  'Shooter',
  'Strategy',
  'Puzzle',
  'Simulation',
  'Fighting',
  'Racing',
  'Survival',
  'Sandbox',
];

//@TODO move this db later
export const TAGS = [
  'Based on True Story',
  'Cult Classic',
  'Binge-worthy',
  'Award-winning',
  'Coming of Age',
  'Post-Apocalyptic',
  'Dystopian',
  'Feel-Good',
  'Dark',
  'Slow Burn',
  'Fast-paced',
  'Character-driven',
  'Plot Twist',
  'Underrated',
  'Critically Acclaimed',
  'Soundtrack Heavy',
  'Visual Masterpiece',
  'Mind-Bending',
  'Satirical',
  'Non-linear Story',
  'Multi-language',
  'Psychological',
  'Time Travel',
  'Violent',
  'Family Friendly',
  'Adult',
  'Romantic',
  'Political',
  'Fantasy World',
  'Supernatural',
  'Historical Fiction',
  'Episodic',
  'Serialized',
  'Minimalist',
  'Dialogue-heavy',
];


//@TODO move this db later
export const GAME_GENRES = [
  'Action',
  'Adventure',
  'RPG',
  'Shooter',
  'Puzzle',
  'Racing',
  'Sports',
  'Strategy',
  'Simulation',
  'Fighting',
  'Stealth',
  'Survival',
  'MMORPG',
  'Indie',
  'Sandbox',
  'Horror',
  'Open World',
  'Rhythm',
  'Card Game',
  'Board Game',
  'Battle Royale',
  'Visual Novel',
  'Metroidvania',
  'Roguelike',
  'Tactical',
  'Point-and-Click',
];

export const GAME_PLATFORMS = [
  'PC',
  'PlayStation 5',
  'PlayStation 4',
  'PlayStation 3',
  'Xbox Series X',
  'Xbox One',
  'Xbox 360',
  'Nintendo Switch',
  'Nintendo Wii U',
  'Nintendo 3DS',
  'Android',
  'iOS',
  'Google Stadia',
  'Amazon Luna',
  'VR',
];

