@baseUrl = http://localhost:3001
@authToken = Bearer <token>

#---------------------------------Games--------------------------------------------------------------------------------------
### get game by id with user context
GET {{baseUrl}}/api/game/696da5c214ab5aefab34a9e1/with-entry
Authorization: {{authToken}}