@baseUrl = http://localhost:3001
@authToken = Beare <token>

#------------------------------------------------ History ---------------------------------------------------
### get all transaction 
GET {{baseUrl}}/api/history
Authorization: {{authToken}}